word=str(input("enter the string: "))
w1=len(word)
counter=1
a=word.count("a")
print(f"number of a: {a}")
v=word.count("v")
if v>=1:
 print(f"number of v: {v}")
j=word.count("j")
if j>=1:
 print(f"number of j: {j}")
j=word.count("j")
if j>=1:
 print(f"number of j: {j}")
b=word.count("b")
if b>=1:
 print(f"number of b: {b}")
c=word.count("c")
if c>=1:
 print(f"number of c: {c}")
d=word.count("d")
if d>=1:
 print(f"number of d: {d}")
e=word.count("e")
if e>=1:
 print(f"number of e: {e}")
f=word.count("f")
if f>=1:
 print(f"number of j: {f}")
g=word.count("g")
if g>=1:
 print(f"number of g: {g}")
h=word.count("h")
print(f"number of h: {h}")
i=word.count("i")
print(f"number of i: {i}")
k=word.count("k")
print(f"number of k: {k}")
l=word.count("l")
print(f"number of l: {l}")
m=word.count("m")
print(f"number of m: {m}")
n=word.count("n")
print(f"number of n: {n}")
o=word.count("o")
print(f"number of 0: {o}")
p=word.count("p")
print(f"number of p: {p}")
q=word.count("q")
print(f"number of q: {q}")
r=word.count("r")
print(f"number of r: {r}")
s=word.count("s")
print(f"number of s: {s}")
t=word.count("t")
print(f"number of t: {t}")
u=word.count("u")
print(f"number of u: {u}")
w=word.count("w")
print(f"number of w: {w}")
x=word.count("x")
print(f"number of x: {x}")
y=word.count("y")
print(f"number of y: {y}")
z=word.count("z")
print(f"number of z: {z}")
